# Generated by Django 5.2.10 on 2026-02-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('eBird_code', models.CharField(db_column='eBird_code', max_length=10, primary_key=True, serialize=False)),
                ('common_name', models.CharField(db_column='common_name', max_length=100)),
                ('scientific_name', models.CharField(db_column='scientific_name', max_length=100)),
                ('extra_name', models.CharField(db_column='extra_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'bird_naming_map',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirdSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_column='filename', max_length=255)),
                ('primary_label', models.CharField(db_column='primary_label', max_length=100)),
                ('secondary_labels', models.JSONField(blank=True, db_column='secondary_labels', default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'metadata',
                'ordering': ['-created_at'],
            },
        ),
    ]
