# Generated by Django 5.2.10 on 2026-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('eBird', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('extra_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sound_description', models.TextField(blank=True, null=True)),
                ('naughty_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bird_naming_map',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['common_name'], name='bird_naming_common__0f3a48_idx'), models.Index(fields=['scientific_name'], name='bird_naming_scienti_013f61_idx')],
            },
        ),
        migrations.CreateModel(
            name='BirdSound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('eBird', models.CharField(max_length=100)),
                ('secondary_labels', models.JSONField(blank=True, default=list)),
                ('station', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_datetime', models.DateTimeField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bird_audio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['eBird'], name='bird_audio_eBird_435f6b_idx'), models.Index(fields=['station'], name='bird_audio_station_5c0248_idx'), models.Index(fields=['recording_datetime'], name='bird_audio_recordi_c1593c_idx')],
            },
        ),
    ]
