# Generated by Django 5.2.10 on 2026-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bird_Sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='birdsound',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='birdsound',
            name='recording_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birdsound',
            name='recording_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='birdsound',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='birdsound',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='common_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bird',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='eBird_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bird',
            name='extra_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birdsound',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='birdsound',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='birdsound',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='birdsound',
            name='primary_label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birdsound',
            name='secondary_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='bird',
            index=models.Index(fields=['common_name'], name='bird_naming_common__0f3a48_idx'),
        ),
        migrations.AddIndex(
            model_name='bird',
            index=models.Index(fields=['scientific_name'], name='bird_naming_scienti_013f61_idx'),
        ),
        migrations.AddIndex(
            model_name='bird',
            index=models.Index(fields=['eBird_code'], name='bird_naming_eBird_c_0149e0_idx'),
        ),
        migrations.AddIndex(
            model_name='birdsound',
            index=models.Index(fields=['primary_label'], name='bird_audio_primary_32b5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='birdsound',
            index=models.Index(fields=['station'], name='bird_audio_station_5c0248_idx'),
        ),
        migrations.AddIndex(
            model_name='birdsound',
            index=models.Index(fields=['recording_datetime'], name='bird_audio_recordi_c1593c_idx'),
        ),
        migrations.AlterModelTable(
            name='birdsound',
            table='bird_audio',
        ),
    ]
