# Generated by Django 5.2.10 on 2026-05-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bird_Sound', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'ordering': ['common_name']},
        ),
    ]
